### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by lixiaopengaxn** [senonwx/mvpretrofitrx#2]
大哥，你这个com.jakewharton.retrofit:retrofit2-rxjava2-adapter:1.0.0'类库稳定吗？

**Comment by chenyacheng** [comment]
你可以上retrofit的github上获取最新的类库。

**Comment by lixiaopengaxn** [comment]
嗯，谢谢




    
    
        
            
                
                    
                        
                    
                    
                        
                            bzzguo
                            
                            
                                
                                    邮箱：bzzguo@qq.com
                                
                        
                    
                
            
        
    
Signature is customized by Netease Mail Master


在2018年08月22日 12:34，yacheng199306 写道： 你可以上retrofit的github上获取最新的类库。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/senonwx/mvpretrofitrx","title":"senonwx/mvpretrofitrx","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/senonwx/mvpretrofitrx"}},"updates":{"snippets":[{"icon":"PERSON","message":"@yacheng199306 in #2: 你可以上retrofit的github上获取最新的类库。"}],"action":{"name":"View Issue","url":"https://github.com/senonwx/mvpretrofitrx/issues/2#issuecomment-414907986"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/senonwx/mvpretrofitrx/issues/2#issuecomment-414907986",
"url": "https://github.com/senonwx/mvpretrofitrx/issues/2#issuecomment-414907986",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [senonwx/mvpretrofitrx] 你好 (#2)",
"sections": [
{
"text": "",
"activityTitle": "**yacheng199306**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@yacheng199306",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"senonwx/mvpretrofitrx\",\n\"issueId\": 2,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"senonwx/mvpretrofitrx\",\n\"issueId\": 2\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/senonwx/mvpretrofitrx/issues/2#issuecomment-414907986"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 370914365\n}"
}
],
"themeColor": "26292E"
}
]
