### ISSUE TITLE
请求的时候，当屏幕旋转或者调用相机拍照，Activity会销毁重建，Fragment中的getView()就会为null，请求的时候getView().bindLifeCycle()就会报错

### ISSUE THREAD

**Issue by Olove0** [senonwx/mvpretrofitrx#3]

**Comment by senonwx** [comment]
你好，这种情况我在封装的时侯没有考虑到，不过这个时候建议你在需要销毁父activity的页面中判断getview是否为空在进行下面的流程

**Comment by senonwx** [comment]
你好，在最近开发中也遇到了，这个问题通常调是在AndroidManifest.xml里给屏幕旋转或调用拍照的activity加上android:configChanges="orientation|keyboardHidden|screenSize" 来解决
