### ISSUE TITLE
您好，错误信息如下

### ISSUE THREAD

**Issue by 13938417646** [senonwx/mvpretrofitrx#6]
java.lang.NullPointerException: Attempt to invoke interface method 'io.reactivex.ObservableTransformer com.ztehealth.ordering.contract.MenuContract$View.bindLifecycle()' on a null object reference at com.ztehealth.ordering.presenter.MenuPresenter.oldLogin(MenuPresenter.java:31)

**Comment by senonwx** [comment]
光看这个信息是看不出来的哦
